### ISSUE TITLE
values_yaml is not base64 encoded

### ISSUE THREAD

**Issue by caleno** [drpebcak/rancher-as-code#5]
Any tips on how I can solve this? 

## Error installing Rio

> Error: expanding app: values_yaml is not base64 encoded:    rio:
>      env:
>      - name: IP_ADDRESSES
>        value: x.x.x.x
> 
> 
>   on main.tf line 28, in resource "rancher2_app" "rio":
>   28: resource "rancher2_app" "rio" {
> 
> 

## rancher2_app "rio"

```
  values_yaml      = <<EOF
rio:
  env:
  - name: IP_ADDRESSES
    value: ${join(",", data.terraform_remote_state.cluster.outputs.worker_addresses)}
EOF
```

> values_yaml - (Optional) values.yaml base64 encoded file content for the app template. If modified, app will be upgraded (string) 

Ref. [rancher2_app](https://www.terraform.io/docs/providers/rancher2/r/app.html#values_yaml)

I tried using '${base64encode("")}' in different ways but without success

**Comment by drpebcak** [comment]
I wouldn't recommend installing Rio this way anymore because the chart is super out of date (Rio is moving to fast for me to maintain this way).

To answer your question though, `rancher2_app` was changed to require base64 encoded content for the `values_yaml` arg.

To use `base64encode()` here, the best thing to do would be to move the values.yaml into a file, and use `templatefile()`

`rio-values.yaml`
```
rio:
  env:
  - name: IP_ADDRESSES
    value: ${ip_addresses}
```

then `values_yaml` becomes:
```
...
values_yaml = base64encode(templatefile("${path.module}/rio-values.yaml", {ip_addresses = join(",", data.terraform_remote_state.cluster.outputs.worker_addresses)}))
...
```

Please note that I wrote this inside the github comment editor, so there might be a few minor tweaks needed to make that work.
